[build]
  command = "pnpm install --no-frozen-lockfile && pnpm build"
  publish = "projects/study-in--london/dist"

[functions]
  directory = "netlify/functions"

[functions."bubbleSync"]
  schedule = "*/15 * * * *"

# For Japan context
[context."japan"]
  publish = "projects/study-in--japan/dist"
  command = "pnpm install --no-frozen-lockfile && pnpm build"
