###############################
# Root-level default (optional fallback)
###############################
[build]
  command = "pnpm install && pnpm tsc --outDir dist-scripts && node dist-scripts/bubble-to-astro-sync.js"
  publish = "."

###############################
# Functions (shared)
###############################
[functions]
  directory = "netlify/functions"

[functions."bubbleSync"]
  schedule = "*/15 * * * *"

###############################
# Context for study-in--japan site
###############################
[context.study-in--japan]
  command = "pnpm install && pnpm tsc --outDir dist-scripts && node dist-scripts/bubble-to-astro-sync.js && pnpm --filter study-in--japan... run build"
  publish = "projects/study-in--japan/dist"
  base = "."

###############################
# Context for study-in--london site
###############################
[context.study-in--london]
  command = "pnpm install && pnpm tsc --outDir dist-scripts && node dist-scripts/bubble-to-astro-sync.js && pnpm --filter study-in--london... run build"
  publish = "projects/study-in--london/dist"
  base = "."
